"""add mentor_skills table

Revision ID: 0e91d0a7169e
Revises: 361e1aa4aeb2
Create Date: 2025-10-13 11:40:01.172544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e91d0a7169e'
down_revision = '361e1aa4aeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('date_label', sa.String(length=32), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_skills_mentor_id'), ['mentor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentor_skills_skill_id'), ['skill_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_mentor_id'), ['mentor_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'mentors', ['mentor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_payments_mentor_id'))
        batch_op.drop_index(batch_op.f('ix_payments_kind'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('mentor_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_mentor_skills_mentor_id'))

    op.drop_table('mentor_skills')
    # ### end Alembic commands ###
