"""create mentor_payments table

Revision ID: 2a2d1aa99222
Revises: 9ab4772e2578
Create Date: 2025-10-26 08:55:27.877246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2d1aa99222'
down_revision = '9ab4772e2578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_payments_mentor_id'), ['mentor_id'], unique=False)

    with op.batch_alter_table('mentor_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_skills_mentor_id'))
        batch_op.drop_index(batch_op.f('ix_mentor_skills_skill_id'))

    op.drop_table('mentor_skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), nullable=False),
    sa.Column('skill_id', sa.INTEGER(), nullable=False),
    sa.Column('date_label', sa.VARCHAR(length=32), nullable=True),
    sa.Column('hours', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentor_skills_mentor_id'), ['mentor_id'], unique=False)

    with op.batch_alter_table('mentor_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_payments_mentor_id'))

    op.drop_table('mentor_payments')
    # ### end Alembic commands ###
