"""add mentor avatar

Revision ID: 730e10ae2b6c
Revises: 4980eba3b2ab
Create Date: 2025-10-11 10:47:41.432984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730e10ae2b6c'
down_revision = '4980eba3b2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
