"""add enrollment_id to installment_plans

Revision ID: 88d0d7348c71
Revises: 0257d4d1dcef
Create Date: 2025-10-30 12:19:12.048197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d0d7348c71'
down_revision = '0257d4d1dcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=False),
    sa.Column('use_cheques', sa.Boolean(), nullable=False),
    sa.Column('cheque_fee_percent', sa.Float(), nullable=False),
    sa.Column('cheque_fee_total', sa.Float(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_plans_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_student_id'), ['student_id'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('amount_base', sa.Float(), nullable=False),
    sa.Column('cheque_fee_amount', sa.Float(), nullable=False),
    sa.Column('amount_total', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('cheque_number', sa.String(length=120), nullable=True),
    sa.Column('cheque_bank', sa.String(length=120), nullable=True),
    sa.Column('cheque_issuer', sa.String(length=120), nullable=True),
    sa.Column('cheque_issue_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installments_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installments_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installments_plan_id'))
        batch_op.drop_index(batch_op.f('ix_installments_payment_id'))

    op.drop_table('installments')
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_course_id'))

    op.drop_table('installment_plans')
    # ### end Alembic commands ###
