"""add skills tables

Revision ID: bdadd124940d
Revises: 7441a767a656
Create Date: 2025-10-09 13:05:45.226826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdadd124940d'
down_revision = '7441a767a656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_skill_name_type')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_type'), ['type'], unique=False)

    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('date_label', sa.String(length=32), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_skills_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_skills_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_skills_skill_id'))

    op.drop_table('student_skills')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_type'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    # ### end Alembic commands ###
