"""add created_at to payments

Revision ID: c48b8a3c761e
Revises: 4f265e612e3d
Create Date: 2025-10-20 11:54:31.937907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48b8a3c761e'
down_revision = '4f265e612e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_attendances')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_attend_session_student'), type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('mentor_share_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('mentor_share_percent_int')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_student_course', ['student_id', 'course_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_payments_kind'))
        batch_op.drop_index(batch_op.f('ix_payments_type'))
        batch_op.create_index(batch_op.f('ix_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'mentors', ['mentor_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=8), server_default=sa.text("'IN'"), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_course_id'))
        batch_op.create_index(batch_op.f('ix_payments_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_kind'), ['kind'], unique=False)
        batch_op.alter_column('note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('kind',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_course', type_='unique')
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_share_percent_int', sa.INTEGER(), nullable=True))
        batch_op.alter_column('mentor_share_percent',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_attend_session_student'), ['session_id', 'student_id'])

    op.create_table('_alembic_tmp_attendances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), server_default=sa.text("'PRESENT'"), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
