"""add plan_id FK to installments

Revision ID: ccea691baeac
Revises: a1b2c3d4e5f6
Create Date: 2025-10-29 09:14:29.683911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccea691baeac"
down_revision = "76e5bad24cd9"  # ← بعد از فایل شماره 2 بیاید
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('surcharge_percent', sa.Float(), nullable=False),
    sa.Column('surcharge_amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_installments', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('default_inst_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('default_use_cheques', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('default_cheque_fee_percent', sa.Float(), nullable=False))

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cheque_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('issuer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('surcharge_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_installments_course_id'))
        batch_op.drop_index(batch_op.f('ix_installments_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_installments_student_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'installment_plans', ['plan_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('surcharge_percent')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('title')
        batch_op.drop_column('course_id')
        batch_op.drop_column('enrollment_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('surcharge_percent', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'enrollments', ['enrollment_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_installments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installments_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installments_course_id'), ['course_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('surcharge_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('issuer_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('cheque_number')
        batch_op.drop_column('number')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('default_cheque_fee_percent')
        batch_op.drop_column('default_use_cheques')
        batch_op.drop_column('default_inst_count')
        batch_op.drop_column('allow_installments')

    op.drop_table('installment_plans')
    # ### end Alembic commands ###
