"""add installment_cheq table

Revision ID: feb90dec88ba
Revises: 093bbcbfadaa
Create Date: 2025-11-03 13:58:18.713961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb90dec88ba'
down_revision = '093bbcbfadaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_cheques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('cheque_number', sa.String(length=64), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installment_cheques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_cheques_installment_id'), ['installment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_cheques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_cheques_installment_id'))

    op.drop_table('installment_cheques')
    # ### end Alembic commands ###
